### ISSUE TITLE
Output in PCM regardless of codec selected in “Full Processing Mode” in Audio

### ISSUE THREAD

**Issue by Scordem** [v0lt/VirtualDub2#2]
Windows 11 22631.3672
VirtualDub2 v2.1.1.607

In the Save Video dialog, even if I select Change Audio and choose a codec other than PCM and press OK, the codec is fixed at PCM.

**Comment by v0lt** [comment]
Show the audio codec selection window. I think your format panel is empty.

**Comment by v0lt** [comment]
Try the test builds from here - https://disk.yandex.ru/d/R3Ob8yREy4ChvA

**Comment by Scordem** [comment]
I have confirmed that it has been fixed.
Thank you so much.
