### ISSUE TITLE
сломан парсинг MP4 (или AVC?) - на прошлой версии тоже.

### ISSUE THREAD

**Issue by elstaar** [v0lt/VirtualDub2#4]
Любой mp4 с H264/AVC + AAC, полученный с youtube (и, наверное, не только). Дублируется первый GOP (от I-фрейма до следующего I-фрейма), если прыгать на следующий I-фрейм через shift-> .  Дополнительно, рассинхронизация звука (ведь сдвигается только видео) вместе с неправильным позиционированием. Видео сдвигается всегда, не обязательно прыгать на этот конкретный I-фрейм, просто так заметней всего...

Идентичный файл, открытый в 44282 

![image](https://github.com/user-attachments/assets/a4a92b48-d66b-4efb-9f8c-2d340460776d)

и 2.1.1.607

![image](https://github.com/user-attachments/assets/a5fae2fd-c6a9-4676-ba5a-472d1a3ee439)

https://www.youtube.com/watch?v=A3LrRg1Hc3E получено отсюда через yt-dlp -f 137+140

На mkv (VP9+AAC) такой проблемы нет...

**Comment by gashtal** [comment]
Experiencing the same problem: first GOP is duplicated and the video is always one GOP behind actual playback after that. Issue is definitely related to the avlib plugin. Using the plugin file from VirtualDub2 44282 fixes the issue.

**Comment by Dean-Corso** [comment]
Yes, I see the same problem about using the avlib-1.vdplugin in your package as @gashtal said already. Also the audio wave track is not showing for some files when using your avlib-1.vdplugin version. 

So beside of updating the avlib-1.vdplugin, is there anything new in your VD2 version compared to VD2 version (VirtualDub2_44282) from sourceforge / Anton Shekhovtsov? I mean about editing? Still not working to edit / cut by keyframes only and to export the result without encoding (like I can do in AviDemux).

**Comment by v0lt** [comment]
> So beside of updating the avlib-1.vdplugin, is there anything new in your VD2 version compared to VD2 version (VirtualDub2_44282) from sourceforge / Anton Shekhovtsov?

https://github.com/v0lt/VirtualDub2/blob/master/docs/Changes.txt

**Comment by v0lt** [comment]
[avlib_vdplugin](https://github.com/v0lt/avlib_vdplugin) repository.

**Comment by gashtal** [comment]
@v0lt This bug still exists in the new v2.1.2.663. Can you please clarify why this issue was closed?

**Comment by v0lt** [comment]
This is not a VirtualDub2 problem. The problem is in the [avlib_vdplugin](https://github.com/v0lt/avlib_vdplugin).
